### ISSUE TITLE
Camera doesn't get closer to player and goes through terrain, causing occlusion culling of the whole map

### ISSUE THREAD

**Issue by DanielZ15** [koyoki/fof-issues#110]
![4c6fedc6-4224-11e6-8ae8-4716bcb5c0dc](https://cloud.githubusercontent.com/assets/12484473/16850532/81c16718-49f7-11e6-94cd-48e9608881fd.jpg)

**Comment by andzdroid** [comment]
The baked occlusion might be the problem here. The monkey doesn't build lighting and occlusion, so if they are out of date then you'll need to build them and then commit them to git.

**Comment by DanielZ15** [comment]
I see. Isn't there though also some issue that the 3rd person camera itself is going into the terrain in this case?

**Comment by andzdroid** [comment]
Yes, that is also an issue. Some game objects in the level are not in the Level layer, so the camera does not detect them as obstacles and goes inside them. For example some of the hills around the edge of the map like in the screenshot.

But I also get a similar issue out in the open where my camera is not in anything. That is caused by the baked occlusion map I think.

**Comment by DanielZ15** [comment]
This looks like it's specifically related to the map, lowering priority
