### ISSUE TITLE
No countdown in NAM map

### ISSUE THREAD

**Issue by TarekA112** [koyoki/fof-issues#84]
Contrary to the Hawkland Map, in the NAM map, the time does not descend it ascends and has no limit. 

Should descend from 5min to 0min.

**Comment by jorgebarredo** [comment]
Games cannot be a draw for now, so one of the teams need to win. In attack - defend mode, the attackers don't win unless they capture and there is a time limit for it (so we have a counter down). In King of the Hill maps we cannot have a counter down because one of the teams need to win.

So this is not bug, it is a feature instead and should be in trello instead if we want to do something about it.

**Comment by TarekA112** [comment]
Moved to Trello
